groups: []
resources:
- name: deploy-src
  type: git
  source:
    branch: master
    uri: https://github.com/govau/cga-deploy-k8s
- name: charts
  type: git
  source:
    branch: master
    uri: https://github.com/helm/charts
- name: ops-terraform
  type: git
  source:
    branch: master
    paths:
    - terraform/*.tf
    - terraform/**/*.tf
    - terraform/*.pub
    - terraform/**/*.pub
    - terraform/*.tpl
    - terraform/**/*.tpl
    private_key: ((ops-git-deploy-key.private_key))
    uri: git@github.com:AusDTO/ops.git
- name: ops-installer
  type: git
  source:
    branch: master
    paths:
    - terraform/modules/platform/installer/**
    private_key: ((ops-git-deploy-key.private_key))
    uri: git@github.com:AusDTO/ops.git
- name: tfplan-l
  type: s3
  source:
    access_key_id: ((aws_access_key_id))
    bucket: ((aws_concourse_terraform_bucket))
    region_name: ap-southeast-2
    secret_access_key: ((aws_secret_access_key))
    server_side_encryption: AES256
    versioned_file: l-cld/terraform.tfplan
- name: after-midnight
  type: time
  source:
    location: Australia/Sydney
    start: 12:00 AM
    stop: 1:00 AM
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
jobs:
- name: terraform-force-apply-k
  serial_groups:
  - k
  plan:
  - do:
    - get: ops
      trigger: true
      resource: ops-terraform
    - get: deploy-src
      trigger: true
    - task: create-fake-tfplan
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: govau/cga-cli
        run:
          path: /bin/bash
          args:
          - -c
          - # noop
            # we dont do terraform plan + apply in k-cld, but a tfplan
            # input is still needed by the terraform-apply task
        outputs:
        - name: tfplan
    - task: terraform-apply
      file: deploy-src/ci/terraform-apply.yml
      params:
        AWS_ACCESS_KEY_ID: ((aws_access_key_id))
        AWS_SECRET_ACCESS_KEY: ((aws_secret_access_key))
        ENV_NAME: k
        SKIP_TERRAFORM_PLAN: 1
- name: deploy-k
  serial_groups:
  - k
  plan:
  - do:
    - get: ops
      resource: ops-installer
      trigger: true
    - get: deploy-src
      trigger: true
    - get: charts
    - task: deploy
      file: deploy-src/ci/deploy.yml
      params:
        ALERTMANAGER_SLACK_API_URL: ((alertmanager_slack_api_url))
        AWS_ACCESS_KEY_ID: ((aws_access_key_id))
        AWS_SECRET_ACCESS_KEY: ((aws_secret_access_key))
        ENV_NAME: k
        JUMPBOX_SSH_KEY: ((jumpbox-key.private_key))
        JUMPBOX_SSH_PORT: ((jumpbox-port))
        LETSENCRYPT_EMAIL: ((letsencrypt_email))
        SSO_GOOGLE_CLIENT_SECRET: ((sso_google_client_secret_k))
- name: delete-k
  serial_groups:
  - k
  plan:
  - do:
    - get: ops
      resource: ops-terraform
    - get: deploy-src
    - get: after-midnight
      trigger: true
    - task: delete
      file: deploy-src/ci/delete.yml
      params:
        AWS_ACCESS_KEY_ID: ((aws_access_key_id))
        AWS_SECRET_ACCESS_KEY: ((aws_secret_access_key))
        ENV_NAME: k
- name: terraform-plan-l
  serial_groups:
  - l
  plan:
  - do:
    - get: ops
      passed:
      - terraform-force-apply-k
      resource: ops-terraform
      trigger: true
    - get: deploy-src
      passed:
      - terraform-force-apply-k
      trigger: true
    - task: terraform-plan
      file: deploy-src/ci/terraform-plan.yml
      params:
        AWS_ACCESS_KEY_ID: ((aws_access_key_id))
        AWS_SECRET_ACCESS_KEY: ((aws_secret_access_key))
        ENV_NAME: l
    - put: tfplan-l
      params:
        file: tfplan/terraform.tfplan
- name: terraform-apply-l
  serial_groups:
  - l
  plan:
  - do:
    - get: ops
      passed:
      - terraform-plan-l
      resource: ops-terraform
    - get: deploy-src
      passed:
      - terraform-plan-l
    - get: tfplan
      passed:
      - terraform-plan-l
      resource: tfplan-l
    - task: deploy-apply
      file: deploy-src/ci/terraform-apply.yml
      params:
        AWS_ACCESS_KEY_ID: ((aws_access_key_id))
        AWS_SECRET_ACCESS_KEY: ((aws_secret_access_key))
        ENV_NAME: l
- name: deploy-l
  serial_groups:
  - l
  plan:
  - do:
    - get: ops
      passed:
      - deploy-k
      resource: ops-installer
    - get: deploy-src
      passed:
      - deploy-k
    - get: charts
      passed:
      - deploy-k
    - task: deploy-apply
      file: deploy-src/ci/deploy.yml
      params:
        ALERTMANAGER_SLACK_API_URL: ((alertmanager_slack_api_url))
        AWS_ACCESS_KEY_ID: ((aws_access_key_id))
        AWS_SECRET_ACCESS_KEY: ((aws_secret_access_key))
        ENV_NAME: l
        JUMPBOX_SSH_KEY: ((jumpbox-key.private_key))
        JUMPBOX_SSH_PORT: ((jumpbox-port))
        LETSENCRYPT_EMAIL: ((letsencrypt_email))
        SSO_GOOGLE_CLIENT_SECRET: ((sso_google_client_secret_k))
